import { Match, MatchStatus, League } from './types';

export const MOCK_LEAGUES: League[] = [
  { id: 'nba', name: 'NBA', country: 'USA', flag: '🇺🇸', priority: 1 },
  { id: 'euroleague', name: 'EuroLeague', country: 'Europe', flag: '🇪🇺', priority: 2 },
  { id: 'acb', name: 'Liga ACB', country: 'Spain', flag: '🇪🇸', priority: 3 },
  { id: 'bsl', name: 'Super Ligi', country: 'Turkey', flag: '🇹🇷', priority: 4 },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 'm1',
    leagueId: 'nba',
    leagueName: 'NBA',
    country: 'USA',
    status: MatchStatus.LIVE,
    startTime: new Date().toISOString(),
    currentTime: 'Q4 02:14',
    tv: 'TNT',
    homeTeam: { id: 'lakers', name: 'Los Angeles Lakers', shortName: 'LAL', logo: 'https://picsum.photos/id/10/50/50' },
    awayTeam: { id: 'warriors', name: 'Golden State Warriors', shortName: 'GSW', logo: 'https://picsum.photos/id/20/50/50' },
    homeScore: { q1: 28, q2: 30, q3: 25, q4: 18, total: 101 },
    awayScore: { q1: 32, q2: 28, q3: 29, q4: 22, total: 111 },
    homeStats: { fgPercentage: 45, threePtPercentage: 32, rebounds: 42, assists: 24, turnovers: 12 },
    awayStats: { fgPercentage: 51, threePtPercentage: 42, rebounds: 38, assists: 31, turnovers: 10 },
  },
  {
    id: 'm2',
    leagueId: 'nba',
    leagueName: 'NBA',
    country: 'USA',
    status: MatchStatus.FINISHED,
    startTime: new Date(Date.now() - 7200000).toISOString(),
    tv: 'ESPN',
    homeTeam: { id: 'celtics', name: 'Boston Celtics', shortName: 'BOS', logo: 'https://picsum.photos/id/30/50/50' },
    awayTeam: { id: 'heat', name: 'Miami Heat', shortName: 'MIA', logo: 'https://picsum.photos/id/40/50/50' },
    homeScore: { q1: 30, q2: 30, q3: 28, q4: 25, total: 113 },
    awayScore: { q1: 24, q2: 25, q3: 26, q4: 28, total: 103 },
    homeStats: { fgPercentage: 48, threePtPercentage: 38, rebounds: 45, assists: 26, turnovers: 8 },
    awayStats: { fgPercentage: 42, threePtPercentage: 30, rebounds: 40, assists: 22, turnovers: 14 },
  },
  {
    id: 'm3',
    leagueId: 'euroleague',
    leagueName: 'EuroLeague',
    country: 'Europe',
    status: MatchStatus.SCHEDULED,
    startTime: new Date(Date.now() + 3600000).toISOString(),
    tv: 'EuroLeague TV',
    homeTeam: { id: 'real', name: 'Real Madrid', shortName: 'RMB', logo: 'https://picsum.photos/id/50/50/50' },
    awayTeam: { id: 'barca', name: 'FC Barcelona', shortName: 'FCB', logo: 'https://picsum.photos/id/60/50/50' },
    homeScore: { q1: 0, q2: 0, q3: 0, q4: 0, total: 0 },
    awayScore: { q1: 0, q2: 0, q3: 0, q4: 0, total: 0 },
  },
  {
    id: 'm4',
    leagueId: 'nba',
    leagueName: 'NBA',
    country: 'USA',
    status: MatchStatus.LIVE,
    currentTime: 'Q2 05:45',
    startTime: new Date().toISOString(),
    homeTeam: { id: 'bulls', name: 'Chicago Bulls', shortName: 'CHI', logo: 'https://picsum.photos/id/70/50/50' },
    awayTeam: { id: 'knicks', name: 'New York Knicks', shortName: 'NYK', logo: 'https://picsum.photos/id/80/50/50' },
    homeScore: { q1: 22, q2: 15, q3: 0, q4: 0, total: 37 },
    awayScore: { q1: 28, q2: 18, q3: 0, q4: 0, total: 46 },
    homeStats: { fgPercentage: 40, threePtPercentage: 28, rebounds: 18, assists: 10, turnovers: 6 },
    awayStats: { fgPercentage: 55, threePtPercentage: 45, rebounds: 22, assists: 14, turnovers: 4 },
  }
];